assets:
  settings.xml: "yegor256/home#assets/qulice/settings.xml"
  pubring.gpg: "yegor256/home#assets/pubring.gpg"
  secring.gpg: "yegor256/home#assets/secring.gpg"
  s3cfg: "yegor256/home#assets/s3cfg"

env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"

merge:
  script:
    - "mvn clean install -Pqulice-profile -Pqulice --errors --settings ../settings.xml"
    - "mvn clean site -Psite --errors --settings ../settings.xml"

deploy:
  script:
    - "mvn clean deploy -Pqulice-profile -Pqulice --errors --settings ../settings.xml"
    - "gem install pdd"
    - "mvn clean"
    - "pdd --source=$(pwd) --verbose --file=qulice.xml --exclude=qulice-maven-plugin/src/it/**/*.java"
    - "s3cmd --no-progress put qulice.xml --config=../s3cfg s3://pdd.teamed.io/qulice.xml"

release:
  script:
    - "mvn versions:set \"-DnewVersion=${tag}\""
    - "git commit -am \"${tag}\""
    - "mvn clean deploy -Pqulice-profile -Pqulice -Psonatype --errors --settings ../settings.xml"
    - "mvn clean site-deploy -Pqulice-profile -Psite --errors --settings ../settings.xml"
